/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PTassistant;

import Database.DatabaseManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Panickar
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm(){
        
        initComponents();
        setLocationRelativeTo(null);        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        HeaderLogoLabel = new javax.swing.JLabel();
        InfoLabelHeader2 = new javax.swing.JLabel();
        MiddlePanel = new javax.swing.JPanel();
        LogoHolderPanel = new javax.swing.JPanel();
        LogoHolderLabel = new javax.swing.JLabel();
        LoginContainerPanel = new javax.swing.JPanel();
        UsernameTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JPasswordField();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        ClearFieldsButton = new javax.swing.JButton();
        NormalLoginButton = new javax.swing.JButton();
        FooterPanel = new javax.swing.JPanel();
        CopyrightLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        HeaderPanel.setBackground(new java.awt.Color(22, 37, 47));
        HeaderPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        HeaderLogoLabel.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        HeaderLogoLabel.setForeground(new java.awt.Color(255, 255, 255));
        HeaderLogoLabel.setText("PTassistant");

        InfoLabelHeader2.setFont(new java.awt.Font("Miriam Fixed", 0, 10)); // NOI18N
        InfoLabelHeader2.setForeground(new java.awt.Color(204, 219, 222));
        InfoLabelHeader2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        InfoLabelHeader2.setText("Poly-Technic Attendance Management");

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InfoLabelHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HeaderLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(HeaderLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoLabelHeader2)
                .addGap(38, 38, 38))
        );

        MiddlePanel.setBackground(new java.awt.Color(204, 219, 222));
        MiddlePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        LogoHolderPanel.setBackground(new java.awt.Color(235, 156, 39));
        LogoHolderPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        LogoHolderLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POTAM_Images/1488322116_news.png"))); // NOI18N

        javax.swing.GroupLayout LogoHolderPanelLayout = new javax.swing.GroupLayout(LogoHolderPanel);
        LogoHolderPanel.setLayout(LogoHolderPanelLayout);
        LogoHolderPanelLayout.setHorizontalGroup(
            LogoHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoHolderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoHolderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );
        LogoHolderPanelLayout.setVerticalGroup(
            LogoHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoHolderPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(LogoHolderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        MiddlePanel.add(LogoHolderPanel);

        LoginContainerPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginContainerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        UsernameTextField.setBackground(new java.awt.Color(204, 219, 222));
        UsernameTextField.setFont(new java.awt.Font("Miriam Fixed", 0, 16)); // NOI18N
        UsernameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UsernameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        PasswordTextField.setBackground(new java.awt.Color(204, 219, 222));
        PasswordTextField.setFont(new java.awt.Font("Miriam Fixed", 0, 16)); // NOI18N
        PasswordTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        UsernameLabel.setFont(new java.awt.Font("Miriam Fixed", 0, 16)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(0, 53, 91));
        UsernameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POTAM_Images/1485993826_users-9.png"))); // NOI18N
        UsernameLabel.setText("Username");

        PasswordLabel.setFont(new java.awt.Font("Miriam Fixed", 0, 16)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(0, 53, 91));
        PasswordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POTAM_Images/1485993718_Programming_Development_keywords.png"))); // NOI18N
        PasswordLabel.setText("Password");

        ClearFieldsButton.setBackground(new java.awt.Color(204, 204, 204));
        ClearFieldsButton.setFont(new java.awt.Font("Miriam Fixed", 1, 12)); // NOI18N
        ClearFieldsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POTAM_Images/1485992392_free-38.png"))); // NOI18N
        ClearFieldsButton.setText("Clear Fields");
        ClearFieldsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearFieldsButtonActionPerformed(evt);
            }
        });

        NormalLoginButton.setBackground(new java.awt.Color(202, 74, 9));
        NormalLoginButton.setFont(new java.awt.Font("Miriam Fixed", 1, 16)); // NOI18N
        NormalLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        NormalLoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POTAM_Images/1485992246_user.png"))); // NOI18N
        NormalLoginButton.setText("Login");
        NormalLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NormalLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginContainerPanelLayout = new javax.swing.GroupLayout(LoginContainerPanel);
        LoginContainerPanel.setLayout(LoginContainerPanelLayout);
        LoginContainerPanelLayout.setHorizontalGroup(
            LoginContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginContainerPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(LoginContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(LoginContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(LoginContainerPanelLayout.createSequentialGroup()
                .addGroup(LoginContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginContainerPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(NormalLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginContainerPanelLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(ClearFieldsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginContainerPanelLayout.setVerticalGroup(
            LoginContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginContainerPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(LoginContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(LoginContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginContainerPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginContainerPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addComponent(NormalLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ClearFieldsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        MiddlePanel.add(LoginContainerPanel);

        FooterPanel.setBackground(new java.awt.Color(22, 37, 47));
        FooterPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        CopyrightLabel.setFont(new java.awt.Font("Miriam Fixed", 0, 14)); // NOI18N
        CopyrightLabel.setForeground(new java.awt.Color(204, 204, 204));
        CopyrightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CopyrightLabel.setText(" © TidyCrow  2017 ");

        javax.swing.GroupLayout FooterPanelLayout = new javax.swing.GroupLayout(FooterPanel);
        FooterPanel.setLayout(FooterPanelLayout);
        FooterPanelLayout.setHorizontalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
            .addGroup(FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CopyrightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE))
        );
        FooterPanelLayout.setVerticalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
            .addGroup(FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterPanelLayout.createSequentialGroup()
                    .addContainerGap(27, Short.MAX_VALUE)
                    .addComponent(CopyrightLabel)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MiddlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
            .addComponent(FooterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(MiddlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(FooterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NormalLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NormalLoginButtonActionPerformed
        // TODO add your handling code here:
        
        setLogin();
       
    }//GEN-LAST:event_NormalLoginButtonActionPerformed

    private void ClearFieldsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearFieldsButtonActionPerformed
        //Clearing the username and textfields
        UsernameTextField.setText(null);
        PasswordTextField.setText(null);
    }//GEN-LAST:event_ClearFieldsButtonActionPerformed

    private void setLogin(){
        
        // read credentials from text fields
        String userName = UsernameTextField.getText();
        String password = PasswordTextField.getText();
        
        // check both fields are enterd
        if(!userName.equals("") && !password.equals("")){
            
            DatabaseManager dbManager;
            
            try {
                
                dbManager              = new DatabaseManager();
                ResultSet userDetails  = dbManager.getUserWith(userName, password);
                // check existance of user
                if (userDetails.isBeforeFirst()){
                   if( userDetails.next() ){ 
                        
                      System.out.println(userDetails.getString("Previlege"));
                       switch (userDetails.getString("Previlege")) {
                         case "principal":
                             PrincipalHome princiHome = new PrincipalHome();
                             princiHome.setVisible(true);
                             dispose();

                             break;
                         case "hod":
                             
                             String hodRegId = userName.substring(1);
                             int hodId       = dbManager.getHodIdFromRegId(hodRegId);
                             if(hodId > 0){
                                 System.out.println("hod id =" + hodId);
                                 HODForm form;
                                 form = new HODForm(hodId);
                                 form.setVisible(true);
                                 dispose();
                                                                 
                             }
                             else{
                                 JOptionPane.showMessageDialog(null,"Not a valid user");
                             }
                             
                             break;
                         case "teacher":
                             
                             String teacherRegId = userName.substring(1);
                             int teacherId       = dbManager.getTeacherIdFromRegId(teacherRegId);
                             if(teacherId > 0){
                                 System.out.println("teacher id =" + teacherId);
                                 TeacherForm form;
                                 form = new TeacherForm(teacherId);
                                 form.setVisible(true);
                                 dispose();
                                                                 
                             }
                             else{
                                 JOptionPane.showMessageDialog(null,"Not a valid user");
                             }

                             break;
                         case "student":
                             String studentRegId = userName.substring(1);
                             int studentId       = dbManager.getStudentIdFromRegId(studentRegId);
                             if(studentId > 0){
                                 System.out.println("Student id =" + studentId);
                                 StudentForm form;
                                 form = new StudentForm(studentId);
                                 form.setVisible(true);
                                 dispose();
                                                                 
                             }
                             else{
                                 JOptionPane.showMessageDialog(null,"Not a valid user");
                             }
                             break;
                             
                         default:
                             JOptionPane.showMessageDialog(null,"Not a valid user"); 
                         }
                   }
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Incorrect username or password!");
                }
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }else{
            
            JOptionPane.showMessageDialog(rootPane," Please enter user name and password");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       new LoginForm().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearFieldsButton;
    private javax.swing.JLabel CopyrightLabel;
    private javax.swing.JPanel FooterPanel;
    private javax.swing.JLabel HeaderLogoLabel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel InfoLabelHeader2;
    private javax.swing.JPanel LoginContainerPanel;
    private javax.swing.JLabel LogoHolderLabel;
    private javax.swing.JPanel LogoHolderPanel;
    private javax.swing.JPanel MiddlePanel;
    private javax.swing.JButton NormalLoginButton;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    // End of variables declaration//GEN-END:variables
}
